### ISSUE TITLE
comment score is not visible to other users?

### ISSUE THREAD

**Issue by collinanderson** [minimaxir/hacker-news-undocumented#14]
it says "the comment score is not visible to users other than the author"

isn't it possible to see the score if you collapse the comment?

**Comment by tedmiston** [comment]
The number to the right when you collapse a comment is the number of comments that are hidden by collapsing.

**Comment by collinanderson** [comment]
Ahh, good to know. Is that documented?

**Comment by tedmiston** [comment]
Let's see if the maintainer chimes in about this one — I don't have a strong feeling either way.

**Comment by vitorgalvao** [comment]
I don’t think this one is worth adding. Before collapsing it says `[-]`, and after it says `[+x]` (`x` being the number of comments). I doubt the amount of times it cause confusion is higher than the amount of times it did not.

**Comment by minimaxir** [comment]
It might be worth clarifying what the `x` means.

**Comment by tedmiston** [comment]
I just sent a small PR https://github.com/minimaxir/hacker-news-undocumented/pull/17 that covers this.

**Comment by collinanderson** [comment]
Thanks!
