### ISSUE TITLE
Changing color of top bar

### ISSUE THREAD

**Issue by montanaflynn** [minimaxir/hacker-news-undocumented#5]
I'm not positive how it's unlocked but I've heard users with more than 250 karma can change the color of the top bar. HN even has a page dedicated to showing color possibilities and their hex code.

https://news.ycombinator.com/topcolors

<img width="282" alt="screen shot 2018-02-22 at 9 03 11 am" src="https://user-images.githubusercontent.com/24260/36552674-4a563b5a-17af-11e8-934a-f06ed5c2ac20.png">
<img width="521" alt="screen shot 2018-02-22 at 9 02 57 am" src="https://user-images.githubusercontent.com/24260/36552675-4b0f7250-17af-11e8-9d60-5af414401ae4.png">

**Comment by finnoleary** [comment]
You might also want to add information about the black bar, it's referenced in this post: https://news.ycombinator.com/item?id=14119519

**Comment by abhisuri97** [comment]
I can confirm this is the case.

**Comment by minimaxir** [comment]
Top bar info added in #7 

I'll add a separate note about the black bar.
