### ISSUE TITLE
Claim that https://news.ycombinator.com/topcolors is "the complete set of colors users have set" is false

### ISSUE THREAD

**Issue by ExplodingCabbage** [minimaxir/hacker-news-undocumented#68]
It doesn't contain mine (#64BFBD).

![image](https://github.com/minimaxir/hacker-news-undocumented/assets/2358339/d7287fb3-22c2-4a9f-a4a7-be89382671d6)

... or at least it didn't when I started typing this issue, but my color appeared in the list shortly afterwards! I wonder if that list contains the top colors of *currently active* users?

**Comment by minimaxir** [comment]
Clarified per dang's comment.
